from OpenGL.GLUT import *

WINDOW_WIDTH = 1920
WINDOW_LENGTH = 1000

PADDLE_WIDTH = 10
PADDLE_LENGTH = 100
PADDING = 50


BALL_WIDTH = 20
BALL_HEIGHT = 20

PADDLE_SPEED = 30
BALL_VELOCITY = 12
ACCELARATION = 0.001


FPS = 60
FRAME_TIME = 1 / FPS

FONT = GLUT_BITMAP_TIMES_ROMAN_24
GAME_START = 0
GAME_PLAYING = 1
PLAYER_ONE_WIN = 2
PLAYER_TWO_WIN = 2

END_SCORE = 5

START_MESSAGE_X = WINDOW_WIDTH / 2 - 2 * PADDING
START_MESSAGE_Y = WINDOW_LENGTH / 2

SCORE_MESSAGE_X = WINDOW_WIDTH / 2 - 25
SCORE_MESSAGE_Y = WINDOW_LENGTH - PADDING

SINGLE_PLAYER = 0
MULTI_PLAYER = 1 

CPU_PLAYER_SPEED = 5

SPAWN_DELAY = 0.5

ACTIVE_MODE = SINGLE_PLAYER 
